// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rshafikov/gophermart/internal/client (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_accrual_client.go -package=mocks github.com/rshafikov/gophermart/internal/client Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	schemas "github.com/rshafikov/gophermart/internal/schemas"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetOrderStatus mocks base method.
func (m *MockClient) GetOrderStatus(ctx context.Context, number string) (*schemas.AccrualOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStatus", ctx, number)
	ret0, _ := ret[0].(*schemas.AccrualOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderStatus indicates an expected call of GetOrderStatus.
func (mr *MockClientMockRecorder) GetOrderStatus(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStatus", reflect.TypeOf((*MockClient)(nil).GetOrderStatus), ctx, number)
}
