// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rshafikov/gophermart/internal/handlers (interfaces: balanceService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_balance_service.go -package=mocks github.com/rshafikov/gophermart/internal/handlers balanceService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/rshafikov/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockbalanceService is a mock of balanceService interface.
type MockbalanceService struct {
	ctrl     *gomock.Controller
	recorder *MockbalanceServiceMockRecorder
	isgomock struct{}
}

// MockbalanceServiceMockRecorder is the mock recorder for MockbalanceService.
type MockbalanceServiceMockRecorder struct {
	mock *MockbalanceService
}

// NewMockbalanceService creates a new mock instance.
func NewMockbalanceService(ctrl *gomock.Controller) *MockbalanceService {
	mock := &MockbalanceService{ctrl: ctrl}
	mock.recorder = &MockbalanceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbalanceService) EXPECT() *MockbalanceServiceMockRecorder {
	return m.recorder
}

// GetUserBalance mocks base method.
func (m *MockbalanceService) GetUserBalance(ctx context.Context, userID int) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", ctx, userID)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockbalanceServiceMockRecorder) GetUserBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockbalanceService)(nil).GetUserBalance), ctx, userID)
}

// GetWithdrawalsByUser mocks base method.
func (m *MockbalanceService) GetWithdrawalsByUser(ctx context.Context, id int) ([]*models.Wd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsByUser", ctx, id)
	ret0, _ := ret[0].([]*models.Wd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsByUser indicates an expected call of GetWithdrawalsByUser.
func (mr *MockbalanceServiceMockRecorder) GetWithdrawalsByUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsByUser", reflect.TypeOf((*MockbalanceService)(nil).GetWithdrawalsByUser), ctx, id)
}

// IncreaseUserBalance mocks base method.
func (m *MockbalanceService) IncreaseUserBalance(ctx context.Context, userID int, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseUserBalance", ctx, userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseUserBalance indicates an expected call of IncreaseUserBalance.
func (mr *MockbalanceServiceMockRecorder) IncreaseUserBalance(ctx, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseUserBalance", reflect.TypeOf((*MockbalanceService)(nil).IncreaseUserBalance), ctx, userID, amount)
}

// Withdraw mocks base method.
func (m *MockbalanceService) Withdraw(ctx context.Context, balance *models.Balance, withdrawal *models.Wd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, balance, withdrawal)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockbalanceServiceMockRecorder) Withdraw(ctx, balance, withdrawal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockbalanceService)(nil).Withdraw), ctx, balance, withdrawal)
}
