// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rshafikov/gophermart/internal/models (interfaces: BalanceService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_balance_service.go -package=mocks github.com/rshafikov/gophermart/internal/models BalanceService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/rshafikov/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceService is a mock of BalanceService interface.
type MockBalanceService struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceServiceMockRecorder
	isgomock struct{}
}

// MockBalanceServiceMockRecorder is the mock recorder for MockBalanceService.
type MockBalanceServiceMockRecorder struct {
	mock *MockBalanceService
}

// NewMockBalanceService creates a new mock instance.
func NewMockBalanceService(ctrl *gomock.Controller) *MockBalanceService {
	mock := &MockBalanceService{ctrl: ctrl}
	mock.recorder = &MockBalanceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceService) EXPECT() *MockBalanceServiceMockRecorder {
	return m.recorder
}

// ChangeUserBalance mocks base method.
func (m *MockBalanceService) ChangeUserBalance(ctx context.Context, newBalance *models.Balance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserBalance", ctx, newBalance)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeUserBalance indicates an expected call of ChangeUserBalance.
func (mr *MockBalanceServiceMockRecorder) ChangeUserBalance(ctx, newBalance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserBalance", reflect.TypeOf((*MockBalanceService)(nil).ChangeUserBalance), ctx, newBalance)
}

// GetUserBalance mocks base method.
func (m *MockBalanceService) GetUserBalance(ctx context.Context, userID int) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", ctx, userID)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockBalanceServiceMockRecorder) GetUserBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockBalanceService)(nil).GetUserBalance), ctx, userID)
}

// GetWithdrawalsByUser mocks base method.
func (m *MockBalanceService) GetWithdrawalsByUser(ctx context.Context, id int) ([]*models.Wd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsByUser", ctx, id)
	ret0, _ := ret[0].([]*models.Wd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsByUser indicates an expected call of GetWithdrawalsByUser.
func (mr *MockBalanceServiceMockRecorder) GetWithdrawalsByUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsByUser", reflect.TypeOf((*MockBalanceService)(nil).GetWithdrawalsByUser), ctx, id)
}

// Withdraw mocks base method.
func (m *MockBalanceService) Withdraw(ctx context.Context, balance *models.Balance, withdrawal *models.Wd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, balance, withdrawal)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockBalanceServiceMockRecorder) Withdraw(ctx, balance, withdrawal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockBalanceService)(nil).Withdraw), ctx, balance, withdrawal)
}
