version: '3'

env:
  BIN_DIR: cmd/gophermart
  BIN_NAME: main
  BIN_PATH: "{{.BIN_DIR}}/{{.BIN_NAME}}"
  DB_DSN: postgres://postgres:password@localhost:5432/postgres

tasks:
  build:
    desc: "Build bin files"
    cmds:
      - go build -v -o "{{.BIN_PATH}}" "{{.BIN_DIR}}/main.go"

  run:
    desc: "Run server"
    cmds:
      - "./{{.BIN_PATH}} -d {{.DB_DSN}}"

  linter:
    run: once
    cmd: go vet -vettool=`which statictest` ./...
